# Generated by Django 6.0.6 on 2026-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
